<?php
/**
 * Copyright (c) 2012 Vuy_Nick
 * @author Vuy_Nick <lucky_nick@mail.ru>
 * @version 1.0
 */
?>
<script type="text/javascript">
$(document).ready(function(){
	$('#search').focus();
	$('.pic').hover(function(eventObject){
		$(this).stop().animate({width:"240px",height:"320px"}, 800);
	},function(){
		$(this).stop().animate({width:"90px",height:"120px"}, 800);
	});
});
</script>
<?php
if($this->idetity){
	$name = $this->idetity->u_role;
}else{
	$name = 'guest';
}
if(count($this->paginator)){
$s1 = 1;
$s2 = 2;
echo '<p>Сортировка:&nbsp &nbsp &nbsp
<a href="/products/index/sort/1/"> + </a>ДАТА<a href="/products/index/sort/2/"> - </a>&nbsp &nbsp<a href="/products/index/sort/3/"> + </a>НАИМЕНОВАНИЕ<a href="/products/index/sort/4/"> - </a>&nbsp &nbsp<a href="/products/index/sort/5/"> + </a>ЦЕНА<a href="/products/index/sort/6/"> - </a></p>';
foreach($this->paginator as $product){
	echo'<p>';
	$p_id = $product['p_id'];
	$p_title = $product['p_title'];
	$pi_img = $product['pi_img'];
	echo "<a href='/products/view/id/$p_id/'><Img id='pic' class='pic' src='/data/images/$pi_img'width='90' height='120'> </a><div id='p_text'>";
	if($name == 'guest' or $name == 'user'){
		echo "<h3><a href='/products/view/id/$p_id/'>ID-$p_id</a></h3><br>";
	}else{
		echo "<h3><a href='/products/view/id/$p_id/'>$p_title</a></h3><br>";
	}
	echo 'Дата добавления: ' . $product['p_created'] . '<br>';
	echo'Цена: ';
	if($name == 'guest'){
		echo round($product['p_price']*$product['guest']*$product['tax'],2);
	}elseif($name == 'user'){
		echo round($product['p_price']*$product['user']*$product['tax'],2);
	}elseif($name == 'user1'){
		echo round($product['p_price']*$product['user1']*$product['tax'],2);
	}elseif($name == 'user2'){
		echo round($product['p_price']*$product['user2']*$product['tax'],2);
	}elseif($name == 'user3'){
		echo round($product['p_price']*$product['user3']*$product['tax'],2);
	}elseif($name == 'admin'){
		echo round($product['p_price']*$product['admin']*$product['tax'],2);
	}
	echo ' гривен';
	echo "<br><br><a href='/user/addtocart/id/$p_id'>В Корзину</a></div>";
	echo'</p><div id="clear"></div>';
	}
echo $this->paginator;
}else{
	echo'<p>Товаров пока нет</p>';
}
?>