<?php
/**
 * Copyright (c) 2012 Vuy_Nick
 * @author Vuy_Nick <lucky_nick@mail.ru>
 * @version 1.0
 */
?>
<p><a href="<?=$this->url(array(
					'controller' => 'admin',
					'action' => 'users'
				))?>">Пользователи</a></p>
<p><a href="<?=$this->url(array(
					'controller' => 'admin',
					'action' => 'catalog'
				))?>">Каталог</a></p>
<p><a href="<?=$this->url(array(
					'controller' => 'admin',
					'action' => 'products'
				))?>">Товары</a></p>