<?php
/**
 * Copyright (c) 2012 Vuy_Nick
 * @author Vuy_Nick <lucky_nick@mail.ru>
 * @version 1.0
 */
?>
<script type="text/javascript">
$(document).ready(function(){
	$('#p_title').focus();
});
</script>
<?php
echo $this->form;
if(count($this->products)){
	foreach($this->products as $product){
		echo $product['p_id'];
		$p_id = $product['p_id'];
		$p_title = $product['p_title'];
		$pi_img = $product['pi_img'];
		echo "<a href='/admin/productview/id/$p_id'><Img id='pic' src='/data/images/$pi_img'Width='90' Height='120'></a><div id='p_text'>";
		echo "<h3><a href='/admin/productview/id/$p_id'>ID-$p_id $p_title</a></h3>";
		echo 'Дата добавления: ' . $product['p_created'] . '<br>';
		echo 'Цена: ' . $product['p_price'] . ' гривен<br>';
		echo 'Количество: ' . $product['p_quantity'] . ' шт.<br>';
		echo 'Действия: ';
		if($product['p_status']){
			echo "<a href='/admin/productactiv/id/$p_id/val/0'> Скрыть </a>";
		}else{
			echo "<a href='/admin/productactiv/id/$p_id/val/1'> Показать </a>";
		}
		echo "<a href='/admin/productedit/id/$p_id'> Редактировать </a>";
		echo "<a href='/admin/productdelete/id/$p_id'> Удалить </a></div>";
		echo'</p>';
	}
}else{
	echo'<p>Товаров пока нет</p>';
}
?>
