<?php
/**
 * Copyright (c) 2012 Vuy_Nick
 * @author Vuy_Nick <lucky_nick@mail.ru>
 * @version 1.0
 */
?>
<script type="text/javascript">
$(document).ready(function(){
	$('#search').focus();
	$('.pic').hover(function(eventObject){
		$(this).stop().animate({width:"240px",height:"320px"}, 800);
	},function(){
		$(this).stop().animate({width:"90px",height:"120px"}, 800);
	});
});
</script>
<?php
if(count($this->paginator)){
	echo '<p>Сортировка:&nbsp &nbsp &nbsp
	<a href="/admin/products/sort/1/"> + </a>ДАТА<a href="/admin/products/sort/2/"> - </a>&nbsp &nbsp<a href="/admin/products/sort/3/"> + </a>НАИМЕНОВАНИЕ<a href="/admin/products/sort/4/"> - </a>&nbsp &nbsp<a href="/admin/products/sort/5/"> + </a>ЦЕНА<a href="/admin/products/sort/6/"> - </a></p>';
	foreach($this->paginator as $product){
		echo'<p>';
		$p_id = $product['p_id'];
		$p_title = $product['p_title'];
		$pi_img = $product['pi_img'];
		echo "<a href='/admin/productview/id/$p_id'><Img id='pic' class='pic' src='/data/images/$pi_img'Width='90' Height='120'></a><div id='p_text'>";
		echo "<h3><a href='/admin/productview/id/$p_id'>ID-$p_id $p_title</a></h3>";
		echo 'Дата добавления: ' . $product['p_created'] . '<br>';
		echo 'Цена: ' . $product['p_price'] . ' гривен<br>';
		echo 'Количество: ' . $product['p_quantity'] . ' шт.<br>';
		echo 'Наценка: ' . $product['name'] . '<br>';
		echo 'Действия: ';
		if($product['p_status']){
			echo "<a href='/admin/productactiv/id/$p_id/val/0'> Скрыть </a>";
		}else{
			echo "<a href='/admin/productactiv/id/$p_id/val/1'> Показать </a>";
		}
		echo "<a href='/admin/productedit/id/$p_id'> Редактировать </a>";
		echo "<a href='/admin/productdelete/id/$p_id'> Удалить </a></div>";
		echo'</p><div id="clear"></div>';
	}
	echo $this->paginator;
}else{
	echo'<p>Товаров пока нет</p>';
}?>
<p><a href="<?php echo $this->url(array(
					'controller' => 'admin',
					'action' => 'productadd'
				));?>">Добавить новый товар</a></p>