<?php
/**
 * Copyright (c) 2012 Vuy_Nick
 * @author Vuy_Nick <lucky_nick@mail.ru>
 * @version 1.0
 */
?>
<h2>Добро пожаловать на наш сайт</h2>

<h3><a href='http://shop/user/confirm/id/<?php echo $this->user->u_id;?>/code/<?php echo $this->user->u_code;?>'>Ссылка для активации Вашего аккаунта: <br>http://shop/user/confirm/id/<?php echo $this->user->u_id;?>/code/<?php echo $this->user->u_code;?></a></h3>